### ISSUE TITLE
Versioning Scheme and First Release

### ISSUE THREAD

**Issue by leograba** [hiagofranco/Brict-ToradexInformationTool#10]
Hi guys,

Do you have any plans to adopt a versioning scheme (e.g. https://semver.org/) and make an initial release?

**Comment by hiagofranco** [comment]
Hi @leograba, 

Not yet, but we could definitely do that. What do you suggest? Do you think this code is ready for a first version release?

**Comment by leograba** [comment]
Hi @hiagofranco,

For versioning, I'd suggest Semantic Versioning (https://semver.org/) because it's widely used across software and proven to work well. They have a section on why to use it, you can evaluate if you think it's suitable for this project: https://semver.org/#why-use-semantic-versioning

Semantic Versioning also answers the question of whether the code is ready for a first version:

> 4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Keeping the major as zero sets the expectations and allows for anything to break at any given point in time.

**Comment by hiagofranco** [comment]
Hi @leograba,

Thank you for the links. I'm thinking of releasing now version 0.1.0 so we can test it on our modules and different BSPs/TorizonCore. Then, we can fix our bugs, improve the code and release 1.0.0 in the future. What do you think about that?

**Comment by leograba** [comment]
It looks good and it leaves room for making other releases with 0.x.y between 0.1.0 and 1.0.0.

**Comment by hiagofranco** [comment]
Here is the release: https://github.com/hiagofranco/Brict-ToradexInformationTool/releases/tag/v0.1.0 :partying_face:
