### ISSUE TITLE
Tool name

### ISSUE THREAD

**Issue by griloHBG** [hiagofranco/Brict-ToradexInformationTool#11]
I understand that the current Brict name is quite short and easy to remember.

But I would like to propose some name that talks by itself.

Maybe `support-helper.sh`

Or `tdx-support-helper.sh`

I really think that this name shows one of the main usages of this tool: to help Toradex support during early (maybe the first) steps of support.

What do you guys think? :)

**Comment by griloHBG** [comment]
Maybe `suphelper.sh` / `tdx-suphelper.sh`

A little word play on the "confusion" between support and support.

**Comment by hiagofranco** [comment]
@leograba since you thought about the name "brict", what do you think about @griloHBG comments? 
I personally agree with him, that "support-helper" is more intuitive (although I think it is a little long, but definitely easier to understand).

Just a reminder @griloHBG, we dropped the ".sh" extension =) Now it's just the name without any extension.

**Comment by griloHBG** [comment]
> Just a reminder @griloHBG, we dropped the ".sh" extension =) Now it's just the name without any extension.

Oh ok. Makes sense :D

**Comment by leograba** [comment]
You guys know customers better, I don't have any additional thoughts to add.

If you'd prefer to rename it to anything more convenient, that sounds good.

**Comment by hiagofranco** [comment]
Thanks, @leograba. @griloHBG I think we need to add "info" or something related to the name, so our customers will know this script will just get their hardware/software info... What do you think?

**Comment by hiagofranco** [comment]
@griloHBG what do you think about **tdx-info**?

**Comment by hiagofranco** [comment]
Added PR #16

**Comment by hiagofranco** [comment]
Merged #16
