### ISSUE TITLE
Reduce amount of data on default option

### ISSUE THREAD

**Issue by leograba** [hiagofranco/Brict-ToradexInformationTool#13]
Hi guys, this is a proposal.

Currently, the default option behaves the same as `--all`:

> Nothing, “-a“ or “--all“: it’ll print everything.

I'd like to propose that the default (when no option is passed) only print a small subset of data that is almost always required, no matter which bug: basic hardware (whatever `--hardware` prints) and software summary (whatever `--software` prints).

**Comment by hiagofranco** [comment]
Great! I agree with you @leograba. I'll also try to combine it with #14, as you mentioned there, so it will become easier for our customers to run this script.

**Comment by hiagofranco** [comment]
Since it will be easier to just solve this issue first and then solve the #14 issue, I will create a PR to solve what you propose here, and then we can discuss more about #14 later.

**Comment by hiagofranco** [comment]
Added PR #17

**Comment by hiagofranco** [comment]
Merged #17
